Gql01 user create apitests s.swift
Nataliia-Zhemanova/TheBookOfComments2.0.1 pull request #13
Opened 2023-12-12 18:18 UTC by dalaran78

userCreate API tests

2023-12-12 19:05 UTC, dalaran78 commented
Closing this PR as pushed spec file only, without supporting files.  Will open new PR

2023-12-13 21:45 UTC, AzamatMurzabay commented on src/modules/user/_test/userCreate.spec.js
> +        .expect(200)
please change to code 400

2023-12-13 23:36 UTC, AzamatMurzabay requested changes

2023-12-13 23:36 UTC, AzamatMurzabay commented on src/modules/user/_test/userCreateSwi.spec.js
>          .end((err, res) => {
Error: expected 200 "OK", got 400 "Bad Request"

2023-12-13 23:36 UTC, AzamatMurzabay commented on src/modules/user/_test/userCreateSwi.spec.js
>          .end((err, res) => {
Error: expected 200 "OK", got 400 "Bad Request"

2023-12-13 23:36 UTC, AzamatMurzabay commented on src/modules/user/_test/userCreateSwi.spec.js
>            const respData = res.body.data;
The expect have to be an error message as example below: 

const respData = res.body.errors[0]
                    console.log("====", respData)
                    expect(respData.message).eq('GraphQL operations must contain a non-empty `query` or a `persistedQuery` extension.')
                    expect(respData.extensions.code).to.eq('INTERNAL_SERVER_ERROR')

2023-12-13 23:36 UTC, AzamatMurzabay commented on src/modules/user/_test/userCreateSwi.spec.js
>            const respData = res.body.data;
The expect have to be an error message as example below: 

const respData = res.body.errors[0]
                    console.log("====", respData)
                    expect(respData.message).eq('GraphQL operations must contain a non-empty `query` or a `persistedQuery` extension.')
                    expect(respData.extensions.code).to.eq('INTERNAL_SERVER_ERROR')

2023-12-20 16:37 UTC, closed without merging