Gql  api tests nazarenko
Nataliia-Zhemanova/TheBookOfComments2.0.1 pull request #15
Opened 2023-12-13 18:12 UTC by NazarenkoDenis37

2023-12-13 20:28 UTC, slborisova requested changes

2023-12-13 20:28 UTC, slborisova commented on src/modules/user/_test/userCreate.specNaz.js
> +            console.log("RESP BODY ===", respData)
Please, delete console.log

2023-12-13 20:28 UTC, slborisova commented on src/modules/user/_test/userCreate.specNaz.js
> +            console.log("RESP BODY ===", respData)
Please, delete console.log

2023-12-13 20:28 UTC, slborisova commented on src/modules/user/_test/userCreate.specNaz.js
> +            console.log("RESP BODY ===", respData)
Please, delete console.log

2023-12-15 04:37 UTC, NazarenkoDenis37 commented on src/modules/user/_test/userCreate.specNaz.js
> +            console.log("RESP BODY ===", respData)
done

2023-12-15 04:38 UTC, NazarenkoDenis37 commented on src/modules/user/_test/userCreate.specNaz.js
> +            console.log("RESP BODY ===", respData)
done

2023-12-15 04:38 UTC, NazarenkoDenis37 commented on src/modules/user/_test/userCreate.specNaz.js
> +            console.log("RESP BODY ===", respData)
done

2023-12-15 04:42 UTC, slborisova approved these changes

2023-12-15 04:42 UTC, slborisova approved these changes

2023-12-15 04:44 UTC, slborisova approved these changes

2023-12-15 05:15 UTC, slborisova approved these changes

2023-12-15 05:16 UTC, slborisova approved these changes

2023-12-15 05:19 UTC, slborisova approved these changes

2023-12-15 05:21 UTC, slborisova approved these changes

2023-12-15 05:21 UTC, merged