Gql02 user get by id ap itest murzabayev
Nataliia-Zhemanova/TheBookOfComments2.0.1 pull request #31
Opened 2023-12-20 03:07 UTC by AzamatMurzabay

-userCreate
-userDeleteById
-userGetById
- userGetAll
- userUpdateById

2023-12-21 20:03 UTC, Jalalov01 requested changes

2023-12-21 22:37 UTC, AzamatMurzabay commented on src/modules/user/_test/userGetByIdMur.spec.js
> +                    console.log("RESP BODY ===", respData);
done

2023-12-21 22:37 UTC, AzamatMurzabay commented on src/modules/user/_test/userGetByIdMur.spec.js
> +                    console.log("USER ID ===", userId);
done

2023-12-21 22:46 UTC, AzamatMurzabay commented on src/modules/user/_test/userGetByIdMur.spec.js
> +                    console.log("RESP BODY USER GET BY ID ===", respData);
done

2023-12-21 22:46 UTC, AzamatMurzabay commented on src/modules/user/_test/userGetByIdMur.spec.js
> +                    console.log("RESP BODY ===", respData);
done

2023-12-21 22:52 UTC, AzamatMurzabay commented on src/modules/user/_test/userGetByIdMur.spec.js
> +                    const respData = res.body.data;
done

2023-12-21 22:53 UTC, AzamatMurzabay commented on src/modules/user/_test/userGetByIdMur.spec.js
> +                    console.log("RESP BODY USER GET BY ID ===", respData);
done

2023-12-21 22:53 UTC, AzamatMurzabay commented on src/modules/user/_test/userGetByIdMur.spec.js
> +                    console.log("USER ID ===", userId);
done

2023-12-21 22:53 UTC, AzamatMurzabay commented on src/modules/user/_test/userGetByIdMur.spec.js
> +                    // expect (respData.userGetById.lastName).eq(userInput.userInput.lastName);
done

2023-12-22 20:31 UTC, Jalalov01 commented
All changes verified

2023-12-22 20:38 UTC, Jalalov01 approved these changes

2023-12-22 20:39 UTC, merged