Gql05 user delete by id ap itests mammadli
Nataliia-Zhemanova/TheBookOfComments2.0.1 pull request #34
Opened 2023-12-22 19:52 UTC by itmelia

2023-12-22 21:07 UTC, rustamkutovyi requested changes

2023-12-22 21:07 UTC, rustamkutovyi commented on src/modules/user/_test/usersGetAllMam.spec.js
> +                    expect(respData.usersGetAll.length).not.to.eq(0)
you can add one more expect for response to be an array

2023-12-22 21:07 UTC, rustamkutovyi commented on src/modules/user/_test/usersGetAllMam.spec.js
> +        before('user create', (done) => {
delete before hook for user create, as you are not using it

2023-12-22 21:07 UTC, rustamkutovyi commented on src/modules/user/_test/userGetByIdMam.spec.js
> +                    console.log('GET BY EMPTY ID RESP ===', respData)
delete console

2023-12-22 22:42 UTC, itmelia commented on src/modules/user/_test/userUpdateByIdMam.spec.js
> +        before('user create', (done) => {
Good point! Thanks.

2023-12-22 22:46 UTC, itmelia commented on src/modules/user/_test/usersGetAllMam.spec.js
> +        before('user create', (done) => {
I must leave the user create hook as the database should be empty when testing. To get users, I have to create them first.

2023-12-23 06:01 UTC, rustamkutovyi approved these changes

2023-12-23 06:16 UTC, rustamkutovyi approved these changes

2023-12-23 06:18 UTC, rustamkutovyi approved these changes

2023-12-23 06:23 UTC, rustamkutovyi approved these changes

2023-12-23 06:30 UTC, merged