Gql01 user create ap itests bird
Nataliia-Zhemanova/TheBookOfComments2.0.1 pull request #4
Opened 2023-12-12 04:10 UTC by olgatbird

userCreate API tests

2023-12-17 23:59 UTC, rustamkutovyi requested changes

2023-12-17 23:59 UTC, rustamkutovyi commented on src/modules/user/_test/userCreateBir.spec.js
> +                    console.log("RESP BODY ====", respData)
Please delete console.log

2023-12-17 23:59 UTC, rustamkutovyi commented on src/modules/user/_test/userCreateBir.spec.js
> +                    console.log("====", respData)
Please delete console.log

2023-12-17 23:59 UTC, rustamkutovyi commented on src/modules/user/_test/userCreateBir.spec.js
> +                    console.log("second ====", respData)
Please delete console.log

2023-12-19 00:18 UTC, olgatbird commented on src/modules/user/_test/userCreateBir.spec.js
> +                    console.log("RESP BODY ====", respData)
Rustam,  thanks, I deleted console.log

2023-12-19 00:19 UTC, olgatbird commented on src/modules/user/_test/userCreateBir.spec.js
> +                    console.log("====", respData)
Done

2023-12-19 00:19 UTC, olgatbird commented on src/modules/user/_test/userCreateBir.spec.js
> +                    console.log("second ====", respData)
Done

2023-12-19 00:56 UTC, rustamkutovyi commented on src/modules/user/_test/userCreateBir.spec.js
> +                    console.log("second ====", respData)
Hello Olga! Your code looks good now!

2023-12-19 00:57 UTC, rustamkutovyi approved these changes

2023-12-19 00:59 UTC, olgatbird commented on src/modules/user/_test/userCreateBir.spec.js
> +                    console.log("second ====", respData)
Thank you! So, can you merge it?

2023-12-19 01:15 UTC, olgatbird commented on src/modules/user/_test/userCreateBir.spec.js
> +                    console.log("second ====", respData)
Okay! I resolved them

2023-12-19 01:18 UTC, merged

2023-12-19 01:28 UTC, rustamkutovyi commented
Olga, looks like you merged main into your branch.