Gql04 user delete by id ap itests borisova
Nataliia-Zhemanova/TheBookOfComments2.0.1 pull request #5
Opened 2023-12-12 04:10 UTC by slborisova

userCreate AP tests

2023-12-13 05:03 UTC, dumpdusty approved these changes
good to go

2023-12-13 16:37 UTC, NazarenkoDenis37 requested changes

2023-12-13 16:37 UTC, NazarenkoDenis37 commented on src/modules/user/_test/userCreateBor.spec.js
> +          console.log("RESP BODY ===", respData);
Please delete console.log

2023-12-13 18:13 UTC, slborisova commented on src/modules/user/_test/userCreateBor.spec.js
> +          console.log("RESP BODY ===", respData);
done. thanks!

2023-12-15 04:24 UTC, NazarenkoDenis37 approved these changes

2023-12-15 15:29 UTC, merged